# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package (dry-run)

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - "rollup.config.js"
      - "tsconfig.json"
      - ".github/workflows/npm-publish-dry-run.yml"

concurrency:
  group: npm-pack-dry-run-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.target_commitish }}

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies and build
        run: npm ci

      - name: Make release
        run: npm run build
        id: makeRelease

      - name: Fail job if makeRelease failed
        if: steps.makeRelease.outcome == 'failure'
        run: exit 1

        id: check-build-status
      - name: Pack NPM package
        run: |
          npm pack --dry-run